# Generated by Django 4.1 on 2022-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
