# Generated by Django 4.0.6 on 2022-08-08 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiztaker_timestamp_usersanswer_group_and_more'),
        ('fastest', '0002_remove_usermodels_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodels',
            options={'ordering': ['-rating_global']},
        ),
        migrations.RenameField(
            model_name='usermodels',
            old_name='passed_total_test',
            new_name='passed_total_tests',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='passed_test',
        ),
        migrations.AddField(
            model_name='usermodels',
            name='final_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usermodels',
            name='passed_tests',
            field=models.ManyToManyField(blank=True, related_name='passed_user_set', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='rating_global',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='rating_group',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
