# Generated by Django 4.0.6 on 2022-08-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastest', '0005_rename_final_score_usermodels_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='passed_tests',
        ),
    ]
