# Generated by Django 4.0.6 on 2022-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest', '0006_remove_usermodels_passed_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
