# Generated by Django 4.0.6 on 2022-08-10 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest', '0007_alter_usermodels_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='rating_global',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
