# Generated by Django 4.0.6 on 2022-08-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='completed',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_answer', to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_s', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='score',
            field=models.IntegerField(default=20),
        ),
    ]
