# Generated by Django 4.0.6 on 2022-08-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quiz', '0006_remove_quiztaker_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='usersanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='usersanswer',
            name='quiz_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiztaker'),
        ),
    ]
