# Generated by Django 4.0.6 on 2022-08-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiztaker_timestamp_usersanswer_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='group',
        ),
    ]
