# Generated by Django 4.0.6 on 2022-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiztaker_question_alter_quiztaker_data_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='question',
        ),
        migrations.AddField(
            model_name='usersanswer',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
