# Generated by Django 4.0.6 on 2022-08-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_quiztaker_question_usersanswer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='data_finished',
        ),
    ]
